# Cas Theme Settings
cas.theme.name=\u5FAE\u8BED
cas.theme.description=\u5FAE\u8BED\u4FE1\u606F\u6280\u672F\u6709\u9650\u516C\u53F8\u767B\u5F55\u7CFB\u7EDF
cas.standard.js.file=/js/cas.js,/js/material.js,/themes/standard/js/login.js
cas.standard.css.file=/css/cas.css,/themes/standard/css/standard.css
cas.logo.file=/themes/standard/images/tinyfish.svg
cas.favicon.file=/themes/standard/favicon.ico
cas.drawer-menu.enabled=false
cas.login-side-panel.enabled=true
cas.login-form.terms-of-use.enabled=false
cas.login-form.legend.enabled=false