<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.microfoolish.it.account</groupId>
        <artifactId>cas-server</artifactId>
        <version>7.3.0-SNAPSHOT</version>
    </parent>

    <artifactId>cas-server-support-signin</artifactId>
    <name>cas-server-support-signin</name>
    <packaging>pom</packaging>

    <modules>
        <module>cas-server-support-signin-jdbc</module>
        <module>cas-server-support-signin-jpa</module>
        <module>cas-server-support-signin-api</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>cas-server-core-authentication</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
